[project]
name = "aoc-2024"
version = "0.1.0"
description = "Solutions for advent of code 2024"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "ruff>=0.8.2",
]

[tool.ruff]
include = ["pyproject.toml", "src/**/*.py"]
