[project]
name = "aoc-2024"
version = "0.1.0"
description = "Solutions for advent of code 2024"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
